// <auto-generated />
namespace FamiDesk.Mobile.App.MobileAppService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v4));
        
        string IMigrationMetadata.Id
        {
            get { return "201707292148432_v4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
